<!DOCTYPE html>
<html lang="ru">

<?php
    include_once('templates/blocks/head.php');  
?>
<body>
    <?php
        include_once('templates/blocks/header.php');
    ?>
    <?php
        include_once('templates/blocks/mobile_menu.php');
    ?>
    <main>
        <?php
            include_once('templates/blocks/main_slider.php');
        ?>
        <?php
            include_once('templates/blocks/preview_bytovka.php');
        ?>

        <?php
            include_once('templates/blocks/map.php');
        ?>
        <?php
            include_once('templates/blocks/rent_block.php');
        ?>
        <?php
            include_once('templates/blocks/tech.php');
        ?>
        <?php
            include_once('templates/blocks/calculator.php');
        ?>
        <?php
            include_once('templates/blocks/advantages.php');
        ?>
        <?php
            include_once('templates/blocks/photogallery.php');
        ?>
        <?php
            include_once('templates/blocks/price.php');
        ?>
        <?php
            include_once('templates/blocks/seo-text.php');
        ?>
        <?php
            include_once('templates/blocks/delivery_calculator.php');
        ?>
        <?php
            include_once('templates/blocks/often-question.php');
        ?>
        <?php
            include_once('templates/blocks/order_form.php');
        ?>
        <?php
            include_once('templates/blocks/main_article.php');
        ?>
    </main>
    <?php
        include_once('templates/blocks/footer.php');
    ?>
    <?php
        include_once('templates/blocks/script-js.php');
    ?>
    <?php
        include_once('templates/blocks/modal.php');
    ?>
</body>

</html>